# moon-queen ansi
#
# BLACK       #5a4469   #1a0c47
# RED         #fa4eb2   #fb569b   pink
# GREEN       #134db1   #3461d8   blue
# YELLOW      #b41527   #b00c03   red
# BLUE        #318509   #499123   green
# MAGENTA     #fa9604   #fc8f0c   yellow
# CYAN        #7441ba   #614abf   purple
# WHITE       #7a6199   #aabcea
#
# LIGHTRED    #ff7fd4   #fd8cda
# LIGHTGREEN  #3098d7   #4d8fe5
# LIGHTYELLOW #e03c54   #f72f39
# LIGHTBLUE   #599a01   #7faf3f
# LIGHTMAGENTA#fac529   #fce815
# LIGHTCYAN   #8c4ee2   #8466f5

theme:
  active: Red # current playing song in list
  banner: LightRed # the "spotify-tui" banner on launch
  error_border: LightYellow # error dialog border
  error_text: Yellow # error message text (e.g. "Spotify API reported error 404")
  hint: Yellow # hint text in errors
  hovered: LightYellow # hovered pane border
  inactive: LightRed # borders of inactive panes
  playbar_background: Red # background of progress bar
  playbar_progress: LightRed # filled-in part of the progress bar
  playbar_progress_text: White # song length and time played/left indicator in the progress bar
  playbar_text: Red # artist name in player pane
  selected: Red # a) selected pane border, b) hovered item in list, & c) track title in player
  text: Red # text in panes
  header: Red # header text in panes (e.g. 'Title', 'Artist', etc.)

behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  tick_rate_milliseconds: 250
  enable_text_emphasis: true
  show_loading_indicator: true
  enforce_wide_search_bar: false
  liked_icon: ♥
  shuffle_icon: 🔀
  repeat_track_icon: 🔂
  repeat_context_icon: 🔁
  playing_icon: ▶
  paused_icon: ⏸
  set_window_title: true

keybindings:
  # Key stroke can be used if it only uses two keys:
  # ctrl-q works,
  # ctrl-alt-q doesn't.
  back: "esc"

  jump_to_album: "a"

  # Shift modifiers use a capital letter (also applies with other modifier keys
  # like ctrl-A)
  jump_to_artist_album: "A"

  manage_devices: "d"
  decrease_volume: "-"
  increase_volume: "+"
  toggle_playback: " "
  seek_backwards: "<"
  seek_forwards: ">"
  next_track: "n"
  previous_track: "p"
  copy_song_url: "c"
  copy_album_url: "C"
  help: "?"
  shuffle: "ctrl-s"
  repeat: "r"
  search: "/"
  audio_analysis: "v"
  jump_to_context: "o"
  basic_view: "B"
  add_item_to_queue: "z"
